# Generated by Django 5.1.4 on 2024-12-29 20:33

from django.db import migrations
from django.contrib.postgres.operations import TrigramExtension


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_post_tags'),
    ]

    operations = [
        TrigramExtension()
    ]
